-- AurumTrace — full deploy SQL (generated by scripts/build-deploy-sql.sh)
-- Run once against a FRESH Supabase project (SQL editor or psql).
-- Includes: schema + RLS (0001-0007), role grants, and demo seed data.
-- The Supabase 'authenticated' role already exists — do NOT create it here.

-- ============================================================
-- migrations/0001_init.sql
-- ============================================================
-- 0001_init.sql — Foundations schema: tenancy + append-only audit log.
-- Target: Supabase Postgres. `user`/`actor` ids correspond to auth.users.id
-- (no hard FK to auth.users, so this also applies on a plain Postgres for review/test).

create extension if not exists pgcrypto;

-- Helper schema for tenant-context functions used by RLS policies.
create schema if not exists app;

-- Resolve the active tenant from the request JWT claims. Set per request by:
--   * Supabase PostgREST (request.jwt.claims), or
--   * apps/api, via: select set_config('request.jwt.claims', '<json>', true)
-- Returns NULL when unset, so policies fail closed (no rows).
-- NOTE: the raw claim is `nullif(...,'')` BEFORE the ::jsonb cast. After a
-- `SET LOCAL request.jwt.claims` transaction ends, Postgres reverts the custom
-- GUC to '' (not NULL) on a pooled connection; casting ''::jsonb would error
-- instead of failing closed. Guarding here keeps "no/blank claim => no rows".
create or replace function app.current_tenant_id()
returns uuid
language sql
stable
as $$
  select nullif(
    nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'tenant_id',
    ''
  )::uuid
$$;

create or replace function app.current_user_id()
returns uuid
language sql
stable
as $$
  select nullif(
    nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub',
    ''
  )::uuid
$$;

-- ---- Tenants -------------------------------------------------------------
create table if not exists public.tenants (
  id                uuid primary key default gen_random_uuid(),
  legal_name        text not null,
  licence_authority text not null,
  licence_no        text not null,
  goaml_org_id      text,
  created_at        timestamptz not null default now()
);

-- ---- Memberships (user <-> tenant <-> role) ------------------------------
create table if not exists public.memberships (
  user_id    uuid not null,                       -- auth.users.id
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  role       text not null check (role in ('owner','compliance_officer','staff','auditor')),
  created_at timestamptz not null default now(),
  primary key (user_id, tenant_id)
);

create index if not exists memberships_tenant_idx on public.memberships(tenant_id);

-- ---- Audit entries (append-only, hash-chained) ---------------------------
-- One chain per tenant, ordered by `seq`. `prev_hash`/`hash` are computed by
-- the writer (apps/api) over the canonical core; see packages/shared/audit.ts.
create table if not exists public.audit_entries (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.tenants(id) on delete restrict,
  seq           bigint not null,
  actor_id      uuid,                              -- null = system/AI event
  event         text not null,
  resource_type text,
  resource_id   uuid,
  payload       jsonb not null default '{}'::jsonb,
  prev_hash     char(64) not null,
  hash          char(64) not null,
  created_at    timestamptz not null default now(),
  unique (tenant_id, seq),
  unique (tenant_id, hash)
);

create index if not exists audit_entries_tenant_seq_idx
  on public.audit_entries(tenant_id, seq);

-- ============================================================
-- migrations/0002_rls.sql
-- ============================================================
-- 0002_rls.sql — Row-Level Security. Tenant isolation is enforced HERE, in the
-- database, not in application code (CLAUDE.md). Every policy keys on
-- app.current_tenant_id(); when it is NULL the policies return no rows (fail closed).
--
-- FORCE ensures even the table owner is subject to RLS, so a mis-scoped query
-- from any role cannot cross tenants. The apps/api connection role must NOT have
-- BYPASSRLS.

alter table public.tenants        enable row level security;
alter table public.tenants        force  row level security;
alter table public.memberships    enable row level security;
alter table public.memberships    force  row level security;
alter table public.audit_entries  enable row level security;
alter table public.audit_entries  force  row level security;

-- ---- tenants: a member can see only their own tenant --------------------
drop policy if exists tenants_select on public.tenants;
create policy tenants_select on public.tenants
  for select
  using (id = app.current_tenant_id());

-- ---- memberships: scoped to the active tenant ---------------------------
drop policy if exists memberships_select on public.memberships;
create policy memberships_select on public.memberships
  for select
  using (tenant_id = app.current_tenant_id());

-- ---- audit_entries: read within tenant; insert only within tenant -------
drop policy if exists audit_select on public.audit_entries;
create policy audit_select on public.audit_entries
  for select
  using (tenant_id = app.current_tenant_id());

drop policy if exists audit_insert on public.audit_entries;
create policy audit_insert on public.audit_entries
  for insert
  with check (tenant_id = app.current_tenant_id());

-- No UPDATE or DELETE policy exists => those commands are denied for all
-- non-owner roles. Append-only is hardened further in 0003.

-- ============================================================
-- migrations/0003_audit_append_only.sql
-- ============================================================
-- 0003_audit_append_only.sql — Defense-in-depth for the audit log.
-- RLS already denies UPDATE/DELETE (no policy). This adds two more layers so the
-- log is tamper-evident even if a policy is later mis-added or a privileged role
-- is used: an explicit privilege revoke, and a trigger that hard-blocks mutation.

revoke update, delete on public.audit_entries from public;
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    revoke update, delete on public.audit_entries from authenticated;
  end if;
end $$;

create or replace function app.forbid_audit_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'audit_entries is append-only (% denied)', tg_op
    using errcode = 'check_violation';
end;
$$;

drop trigger if exists audit_entries_no_update on public.audit_entries;
create trigger audit_entries_no_update
  before update on public.audit_entries
  for each row execute function app.forbid_audit_mutation();

drop trigger if exists audit_entries_no_delete on public.audit_entries;
create trigger audit_entries_no_delete
  before delete on public.audit_entries
  for each row execute function app.forbid_audit_mutation();

-- ============================================================
-- migrations/0004_domain_tables.sql
-- ============================================================
-- 0004_domain_tables.sql — Phase 1 core domain model (Step 2).
-- Every table carries tenant_id and is RLS-scoped in 0005. Money is integer fils.
-- PII (customer identity, document bytes) lives here, protected by RLS, never logged.
--
-- Cross-tenant integrity: child tables reference parents by COMPOSITE key
-- (tenant_id, id), not id alone. Parents expose `unique (tenant_id, id)`. This
-- makes the FK itself reject a child whose tenant_id differs from its parent's,
-- so RLS (row visibility) and the FK (relational integrity) can't disagree.

-- Role of the current principal, from the verified JWT claim (for read-only auditor).
create or replace function app.current_actor_role()
returns text
language sql
stable
as $$
  -- Same blank-GUC guard as app.current_tenant_id() (see 0001_init.sql).
  select nullif(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role', '')
$$;

-- ---- Customers (PII) -----------------------------------------------------
create table if not exists public.customers (
  id                uuid primary key default gen_random_uuid(),
  tenant_id         uuid not null references public.tenants(id) on delete restrict,
  full_name         text not null,
  emirates_id       text,
  nationality       text,
  residency_status  text check (residency_status in ('resident','non_resident')),
  date_of_birth     date,
  id_expiry         date,
  risk_rating       text not null default 'unrated'
                    check (risk_rating in ('unrated','low','medium','high')),
  created_at        timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, emirates_id)
);
create index if not exists customers_tenant_idx on public.customers(tenant_id);

-- ---- Cases (the six-stage compliance flow) -------------------------------
create table if not exists public.cases (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.tenants(id) on delete restrict,
  reference     text not null,
  customer_id   uuid,
  stage         smallint not null default 1 check (stage between 1 and 6),
  status        text not null default 'draft'
                check (status in ('draft','in_review','reportable','cleared','filed')),
  aggregate_value_fils bigint,
  created_by    uuid,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, reference),
  foreign key (tenant_id, customer_id)
    references public.customers (tenant_id, id) on delete restrict
);
create index if not exists cases_tenant_idx on public.cases(tenant_id);
create index if not exists cases_customer_idx on public.cases(customer_id);

-- ---- Items (gold being transacted) ---------------------------------------
create table if not exists public.items (
  id                  uuid primary key default gen_random_uuid(),
  tenant_id           uuid not null references public.tenants(id) on delete restrict,
  case_id             uuid not null,
  item_type           text not null check (item_type in ('bar','coins','jewellery','scrap','other')),
  purity_karat        smallint check (purity_karat between 1 and 24),
  weight_grams        numeric(12,3) not null check (weight_grams > 0),
  transaction_type    text not null check (transaction_type in ('buy_from_customer','sell_to_customer')),
  gold_price_fils_per_gram bigint,
  value_fils          bigint,
  created_at          timestamptz not null default now(),
  foreign key (tenant_id, case_id)
    references public.cases (tenant_id, id) on delete cascade
);
create index if not exists items_tenant_idx on public.items(tenant_id);
create index if not exists items_case_idx on public.items(case_id);

-- ---- Screening results (KYC/CDD outcomes) --------------------------------
create table if not exists public.screening_results (
  id               uuid primary key default gen_random_uuid(),
  tenant_id        uuid not null references public.tenants(id) on delete restrict,
  case_id          uuid not null,
  customer_id      uuid,
  run_at           timestamptz not null default now(),
  sanctions_match  boolean not null default false,
  pep_match        boolean not null default false,
  adverse_media    boolean not null default false,
  identity_verified boolean not null default false,
  risk_score       smallint check (risk_score between 0 and 100),
  risk_band        text check (risk_band in ('low','medium','high')),
  reasons          jsonb not null default '[]'::jsonb,
  foreign key (tenant_id, case_id)
    references public.cases (tenant_id, id) on delete cascade,
  foreign key (tenant_id, customer_id)
    references public.customers (tenant_id, id) on delete restrict
);
create index if not exists screening_tenant_idx on public.screening_results(tenant_id);
create index if not exists screening_case_idx on public.screening_results(case_id);

-- ---- Sourcing records (OECD due diligence) -------------------------------
create table if not exists public.sourcing_records (
  id               uuid primary key default gen_random_uuid(),
  tenant_id        uuid not null references public.tenants(id) on delete restrict,
  case_id          uuid not null,
  declaration_type text check (declaration_type in ('customer_owned','dealer_sourced','unknown')),
  oecd_steps       jsonb not null default '{}'::jsonb,
  sourcing_risk    text check (sourcing_risk in ('low','medium','high')),
  created_at       timestamptz not null default now(),
  foreign key (tenant_id, case_id)
    references public.cases (tenant_id, id) on delete cascade
);
create index if not exists sourcing_tenant_idx on public.sourcing_records(tenant_id);
create index if not exists sourcing_case_idx on public.sourcing_records(case_id);

-- ---- Reports (goAML filings — NEVER auto-filed) --------------------------
create table if not exists public.reports (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants(id) on delete restrict,
  case_id     uuid not null,
  report_type text not null check (report_type in ('DPMSR','STR')),
  reference   text,
  status      text not null default 'draft'
              check (status in ('draft','pending_review','filed')),
  value_fils  bigint,
  narrative   text,
  goaml_xml   text,
  filed_at    timestamptz,   -- set only by an explicit human "file" action (Step 8)
  filed_by    uuid,
  created_at  timestamptz not null default now(),
  unique (tenant_id, reference),
  foreign key (tenant_id, case_id)
    references public.cases (tenant_id, id) on delete restrict
);
create index if not exists reports_tenant_idx on public.reports(tenant_id);
create index if not exists reports_case_idx on public.reports(case_id);

-- ---- Documents (metadata; bytes stored encrypted in object storage) ------
create table if not exists public.documents (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.tenants(id) on delete restrict,
  case_id       uuid,
  kind          text not null check (kind in ('id_scan','source_declaration','supporting','other')),
  filename      text not null,
  storage_path  text not null,   -- reference only; bytes encrypted at rest (AES-256-GCM) by apps/api documents service
  content_hash  char(64),
  uploaded_by   uuid,
  uploaded_at   timestamptz not null default now(),
  foreign key (tenant_id, case_id)
    references public.cases (tenant_id, id) on delete cascade
);
create index if not exists documents_tenant_idx on public.documents(tenant_id);
create index if not exists documents_case_idx on public.documents(case_id);

-- ============================================================
-- migrations/0005_domain_rls.sql
-- ============================================================
-- 0005_domain_rls.sql — RLS for all domain tables (Step 2).
-- Same posture as 0002: ENABLE + FORCE, tenant-scoped, fail-closed. Writes
-- additionally require a non-auditor role (auditor is read-only). No DELETE
-- policy => deletes are denied for a conservative, compliance-friendly default.

do $$
declare
  t text;
  domain_tables text[] := array[
    'customers','cases','items','screening_results',
    'sourcing_records','reports','documents'
  ];
begin
  foreach t in array domain_tables loop
    execute format('alter table public.%I enable row level security', t);
    execute format('alter table public.%I force  row level security', t);

    execute format('drop policy if exists %I on public.%I', t || '_select', t);
    execute format(
      'create policy %I on public.%I for select using (tenant_id = app.current_tenant_id())',
      t || '_select', t);

    execute format('drop policy if exists %I on public.%I', t || '_insert', t);
    execute format(
      'create policy %I on public.%I for insert with check (' ||
        'tenant_id = app.current_tenant_id() ' ||
        'and app.current_actor_role() is distinct from ''auditor'')',
      t || '_insert', t);

    execute format('drop policy if exists %I on public.%I', t || '_update', t);
    execute format(
      'create policy %I on public.%I for update ' ||
        'using (tenant_id = app.current_tenant_id() ' ||
              'and app.current_actor_role() is distinct from ''auditor'') ' ||
        'with check (tenant_id = app.current_tenant_id() ' ||
              'and app.current_actor_role() is distinct from ''auditor'')',
      t || '_update', t);
  end loop;
end $$;

-- ============================================================
-- migrations/0006_audit_case_id.sql
-- ============================================================
-- 0006_audit_case_id.sql — add a queryable case dimension to the audit log,
-- so a per-case timeline can be retrieved (Step 9 / Module 6).
--
-- NOTE on integrity: case_id is denormalised QUERY metadata, set once at insert
-- and never changed (audit_entries is append-only — RLS denies UPDATE/DELETE and
-- the 0003 trigger blocks mutation even for a superuser). It is intentionally
-- NOT part of the hashed core (packages/shared/audit.ts), because the hash
-- already covers the immutable record and the row itself cannot be altered after
-- insert, so case_id cannot be tampered without breaking append-only.

alter table public.audit_entries add column if not exists case_id uuid;

create index if not exists audit_entries_case_idx
  on public.audit_entries(tenant_id, case_id);

-- ============================================================
-- migrations/0007_case_occurred_at.sql
-- ============================================================
-- 0007_case_occurred_at.sql — the transaction-occurrence date for a case.
--
-- The reporting-threshold aggregation window must anchor on when the transaction
-- OCCURRED, not when the record was created. This adds an explicit column
-- (defaulting to now() so existing rows + counter intake without an explicit
-- date still work), which intake can set to the real transaction date.
-- Resolves the TODO(compliance) anchor caveat in apps/api threshold.service.

alter table public.cases add column if not exists occurred_at timestamptz not null default now();

-- ============================================================
-- deploy/grants.sql
-- ============================================================
-- grants.sql — base table privileges for the `authenticated` role.
--
-- The API connects as the Supabase `postgres`/pooler user, then `SET LOCAL ROLE
-- authenticated` per request. `authenticated` is NOBYPASSRLS, so RLS restricts
-- every row to the request's tenant. These grants give the role table access;
-- RLS does the isolating. UPDATE/DELETE on audit_entries stay UNGRANTED (the log
-- is append-only; migration 0003 also revokes them), so history cannot be edited.
--
-- Supabase usually auto-grants public tables to `authenticated` via default
-- privileges; this file makes it explicit and independent of that default.

grant usage on schema public, app to authenticated;
grant select on public.tenants, public.memberships to authenticated;
grant select, insert on public.audit_entries to authenticated;
grant select, insert, update on
  public.customers, public.cases, public.items, public.screening_results,
  public.sourcing_records, public.reports, public.documents to authenticated;

-- ============================================================
-- seed.sql (fictional demo tenant + sample case)
-- ============================================================
-- seed.sql — a single demo tenant for local development.
-- NOTE: memberships reference auth.users ids. After creating a user in Supabase
-- Auth, insert a membership row mapping that user to this tenant. Replace the
-- placeholder uuid below with the real auth user id (or use the helper at the bottom).

insert into public.tenants (id, legal_name, licence_authority, licence_no, goaml_org_id)
values (
  '00000000-0000-0000-0000-0000000000a1',
  'Al Noor Gold Trading LLC',
  'DMCC',
  'DMCC-7741',
  'UAE-FIU-44821'
)
on conflict (id) do nothing;

-- Example membership (fill in a real auth.users id):
-- insert into public.memberships (user_id, tenant_id, role)
-- values ('<auth-user-uuid>', '00000000-0000-0000-0000-0000000000a1', 'compliance_officer')
-- on conflict do nothing;

-- Demo customer + case (fictional data, mirrors docs/design).
insert into public.customers
  (id, tenant_id, full_name, emirates_id, nationality, residency_status, risk_rating)
values (
  '00000000-0000-0000-0000-0000000000c1',
  '00000000-0000-0000-0000-0000000000a1',
  'Rashid Al Maktoum', '784-1987-3456712-9', 'UAE', 'resident', 'medium'
)
on conflict (id) do nothing;

insert into public.cases
  (id, tenant_id, reference, customer_id, stage, status, aggregate_value_fils)
values (
  '00000000-0000-0000-0000-00000000ca01',
  '00000000-0000-0000-0000-0000000000a1',
  'AT-2026-000148',
  '00000000-0000-0000-0000-0000000000c1',
  3, 'reportable', 9140000
)
on conflict (id) do nothing;
