#!/usr/bin/env bash
# Concatenate migrations + grants + seed into a single deploy/all.sql that can be
# pasted into the Supabase SQL editor (or run with psql) against a FRESH project.
# Regenerate after changing any migration:  bash scripts/build-deploy-sql.sh
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=deploy/all.sql
{
  echo "-- AurumTrace — full deploy SQL (generated by scripts/build-deploy-sql.sh)"
  echo "-- Run once against a FRESH Supabase project (SQL editor or psql)."
  echo "-- Includes: schema + RLS (0001-0007), role grants, and demo seed data."
  echo "-- The Supabase 'authenticated' role already exists — do NOT create it here."
  echo
  for f in migrations/*.sql; do
    echo "-- ============================================================"
    echo "-- $f"
    echo "-- ============================================================"
    cat "$f"
    echo
  done
  echo "-- ============================================================"
  echo "-- deploy/grants.sql"
  echo "-- ============================================================"
  cat deploy/grants.sql
  echo
  echo "-- ============================================================"
  echo "-- seed.sql (fictional demo tenant + sample case)"
  echo "-- ============================================================"
  cat seed.sql
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
